# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: self-hosted
    strategy:
      matrix:
        java: [ '11' ]

    steps:
      - uses: actions/checkout@v2.5.0
      - name: Set up JDK ${{matrix.java}}
        uses: actions/setup-java@v3.6.0
        with:
          java-version: ${{matrix.java}}
          distribution: 'corretto'
          cache: maven
      - name: Build with Maven Wrapper
        run: ./mvnw -B package
      - name: Build, tag docker with spring boot
        run: ./mvnw spring-boot:build-image -Dspring-boot.build-image.imageName=wlami/petclinic
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: tag and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: petclinic
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker tag wlami/petclinic $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker tag wlami/petclinic $REGISTRY/$REPOSITORY:latest
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:latest
